# /otel/otel-collector-config.yml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
exporters:
  # NOTE: Prior to v0.86.0 use `logging` instead of `debug`.
  debug:
    verbosity: detailed
  otlp/jaeger:
    endpoint: "http://jaeger-all-in-one:4317"
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:9464"
    namespace: flask_tutorial
processors:
  batch:
service:
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlp/jaeger]
      processors: [batch]
    metrics:
      receivers: [otlp]
      exporters: [debug, prometheus]
      processors: [batch]
    logs:
      receivers: [otlp]
      exporters: [debug]
      processors: [batch]